language: java

jdk:
  - openjdk8

install: true

script:
  - mvn clean install -Dmaven.javadoc.skip=false -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)